apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mining.facts@gmail.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-dev
    solvers:
    - http01:
        ingress:
          class: nginx
