apiVersion: v1
kind: ConfigMap
metadata:
  name: general-configmap
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  .env: |-
      OLLAMA_BASE_URL="http://ollama-service:11434"
